### ISSUE TITLE
Sitespeed docker container not working correctly for Apple Silicon (M1, arm64)

### ISSUE THREAD

**Issue by alextiley1** [sitespeedio/docker-browsers#2]
Good day.

I recently changed to a new mac with the M1 Apple Chip.

Sitespeed.io via docker no longer seems to be working for this new architecture. Currently the Sitespeed.io docker containers are only built for the `linux/amd64` platform. This platform is not supported on the new Apple M1 arm64 architecture, and I cannot get the docker container to work correctly running `docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:16.8.0 https://www.sitespeed.io/`, the error I get is the following.

```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Google Chrome 88.0.4324.96
Mozilla Firefox 84.0
Microsoft Edge 89.0.767.0 dev
[2021-02-12 10:10:08] INFO: Versions OS: linux 4.19.104-linuxkit nodejs: v12.16.2 sitespeed.io: 16.8.0 browsertime: 11.4.0 coach: 6.0.1
[2021-02-12 10:10:08] INFO: Running tests using Chrome - 3 iteration(s)
[2021-02-12 10:10:11] INFO: chrome failed to start, trying 2 more time(s): unknown error: Chrome failed to start: crashed.
  (chrome not reachable)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
[2021-02-12 10:10:13] INFO: chrome failed to start, trying 1 more time(s): unknown error: Chrome failed to start: crashed.
  (chrome not reachable)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
[2021-02-12 10:10:15] INFO: chrome failed to start, trying 0 more time(s): unknown error: Chrome failed to start: crashed.
  (chrome not reachable)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
[2021-02-12 10:10:15] ERROR: BrowserError: Could not start chrome with 3 tries
    at SeleniumRunner.start (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:86:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2021-02-12 10:10:15] ERROR: No data to collect
[2021-02-12 10:10:17] INFO: chrome failed to start, trying 2 more time(s): unknown error: Chrome failed to start: crashed.
  (chrome not reachable)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
[2021-02-12 10:10:20] INFO: chrome failed to start, trying 1 more time(s): unknown error: Chrome failed to start: crashed.
  (chrome not reachable)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
[2021-02-12 10:10:22] INFO: chrome failed to start, trying 0 more time(s): unknown error: Chrome failed to start: crashed.
  (chrome not reachable)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
[2021-02-12 10:10:22] ERROR: BrowserError: Could not start chrome with 3 tries
    at SeleniumRunner.start (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:86:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2021-02-12 10:10:22] ERROR: No data to collect
[2021-02-12 10:10:24] INFO: chrome failed to start, trying 2 more time(s): unknown error: Chrome failed to start: crashed.
  (chrome not reachable)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
[2021-02-12 10:10:26] INFO: chrome failed to start, trying 1 more time(s): unknown error: Chrome failed to start: crashed.
  (chrome not reachable)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
[2021-02-12 10:10:28] INFO: chrome failed to start, trying 0 more time(s): unknown error: Chrome failed to start: crashed.
  (chrome not reachable)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
[2021-02-12 10:10:28] ERROR: BrowserError: Could not start chrome with 3 tries
    at SeleniumRunner.start (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:86:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2021-02-12 10:10:28] ERROR: No data to collect
[2021-02-12 10:10:28] ERROR: Caught error from Browsertime TypeError: Cannot read property 'alias' of undefined
    at Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:167:52)
[2021-02-12 10:10:31] INFO: HTML stored in /sitespeed.io/sitespeed-result/www.sitespeed.io/2021-02-12-10-10-08
```

To reproduce this issue on an M1 mac, install the docker preview for M1, then run Sitespeed.io via docker `docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:16.8.0 https://www.sitespeed.io/`, you should see the same error as above.

Adding the `--platform linux/amd64` flag to the `docker run` command, as suggested on the [docker preview known issues](https://docs.docker.com/docker-for-mac/apple-m1/) does suppress the architecture miss match error, but the rest of the errors are the errors after the warning are still there as before. This happens for both the initial preview 7 version of Docker for Mac M1, and the latest version 3.1.0(60984).

From what I understand, the dockerfile is only installing chrome, Firefox and edge for amd64, maybe an architecture check could be added to install the arm64 versions if on an arm platform.

To remove the architecture warning, could the docker container be build for multiple platforms using `docker buildx` and pushed to the Sitespeed.io docker hub? 

These are just suggestions to get a conversation going.

Looking forward to your response.

**Comment by soulgalore** [comment]
Hi @alextiley1 thanks for the feedback! I haven't had the money yet to upgrade personal computer to a M1 yet, it will take a couple of years :)

There's four level of containers that I guess then should be fixed:
* https://hub.docker.com/r/sitespeedio/node install Ubuntu and NodeJS
* https://hub.docker.com/r/sitespeedio/visualmetrics-deps adds dependencies to use Visual Metrics
* https://hub.docker.com/r/sitespeedio/webbrowsers install the browser
* And then the Dockerfile in sitespeed.io adds sitespeed.io

If you have to help out maybe we can try it together, it would be great to get it to work.

**Comment by soulgalore** [comment]
Hi @alextiley1 I've built arm images for all four levels, you can test the Browsertime version 

`docker run --rm -v "$(pwd)":/browsertime sitespeedio/browsertime:test https://www.sitespeed.io/`

The positive thing is that all browser version is printed to the output (the browsers work) but negative thing is that they cannot start. 

Using the Chromdriver log: `docker run --platform linux/arm64 --rm -v "$(pwd)":/browsertime sitespeedio/browsertime:test https://www.sitespeed.io/ -b chrome --chrome.enableChromeDriverLog --chrome.enableVerboseChromeDriverLog  -n 1` the log looks like this:

```
[1613461122.371][INFO]: Starting ChromeDriver 88.0.4324.27 (6347fe8bf1e48bd0c54d07dc55ca011cf40861c9-refs/branch-heads/4324@{#450}) on port 44197
[1613461122.373][INFO]: Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
[1613461122.450][SEVERE]: bind() failed: Cannot assign requested address (99)
[1613461122.452][INFO]: listen on IPv6 failed with error ERR_ADDRESS_INVALID
[1613461122.453][SEVERE]: bind() failed: Address already in use (98)
[1613461122.454][INFO]: listen on IPv4 failed with error ERR_ADDRESS_IN_USE
[1613461122.404][DEBUG]: DevTools HTTP Request: http://localhost:9222/json/version
[1613461122.408][DEBUG]: DevTools HTTP Request failed
[1613461122.459][DEBUG]: DevTools HTTP Request: http://localhost:9222/json/version
[1613461122.461][DEBUG]: DevTools HTTP Request failed
[1613461122.512][DEBUG]: DevTools HTTP Request: http://localhost:9222/json/version
[1613461122.515][DEBUG]: DevTools HTTP Request failed
[1613461122.566][DEBUG]: DevTools HTTP Request: http://localhost:9222/json/version
[1613461122.569][DEBUG]: DevTools HTTP Request failed
[1613461122.625][DEBUG]: DevTools HTTP Request: http://localhost:9222/json/version
[1613461122.628][DEBUG]: DevTools HTTP Request failed
qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
[438:438:0216/073842.649533:ERROR:nacl_fork_delegate_linux.cc(329)] Bad NaCl helper startup ack (0 bytes)
qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
[1613461122.679][DEBUG]: DevTools HTTP Request: http://localhost:9222/json/version
[1613461122.681][DEBUG]: DevTools HTTP Request failed
[408:408:0216/073842.679523:ERROR:browser_dm_token_storage_linux.cc(94)] Error: /etc/machine-id contains 0 characters (32 were expected).
[1613461122.732][DEBUG]: DevTools HTTP Request: http://localhost:9222/json/version
[1613461122.735][DEBUG]: DevTools HTTP Request failed
[408:445:0216/073842.735703:ERROR:file_path_watcher_linux.cc(315)] inotify_init() failed: Function not implemented (38)
[1613461122.786][DEBUG]: DevTools HTTP Request: http://localhost:9222/json/version
[1613461122.789][DEBUG]: DevTools HTTP Request failed
[1613461122.839][DEBUG]: DevTools HTTP Request: http://localhost:9222/json/version
[1613461122.842][DEBUG]: DevTools HTTP Request failed
[1613461122.894][DEBUG]: DevTools HTTP Request: http://localhost:9222/json/version
[1613461122.897][DEBUG]: DevTools HTTP Request failed
[1613461122.952][DEBUG]: DevTools HTTP Request: http://localhost:9222/json/version
[1613461122.955][DEBUG]: DevTools HTTP Request failed
[1613461123.007][DEBUG]: DevTools HTTP Request: http://localhost:9222/json/version
[1613461123.009][DEBUG]: DevTools HTTP Request failed
[1613461123.065][DEBUG]: DevTools HTTP Request: http://localhost:9222/json/version
[1613461123.068][DEBUG]: DevTools HTTP Request failed
[1613461123.120][DEBUG]: DevTools HTTP Request: http://localhost:9222/json/version
[1613461123.123][DEBUG]: DevTools HTTP Request failed
[1613461123.178][DEBUG]: DevTools HTTP Request: http://localhost:9222/json/version
[1613461123.180][DEBUG]: DevTools HTTP Request failed
[1613461123.236][DEBUG]: DevTools HTTP Request: http://localhost:9222/json/version
[1613461123.238][DEBUG]: DevTools HTTP Request failed
[1613461123.289][DEBUG]: DevTools HTTP Request: http://localhost:9222/json/version
[1613461123.292][DEBUG]: DevTools HTTP Request failed
[1613461123.343][DEBUG]: DevTools HTTP Request: http://localhost:9222/json/version
[1613461123.346][DEBUG]: DevTools HTTP Request failed
[1613461123.397][DEBUG]: DevTools HTTP Request: http://localhost:9222/json/version
[1613461123.400][DEBUG]: DevTools HTTP Request failed
[1613461123.453][DEBUG]: DevTools HTTP Request: http://localhost:9222/json/version
[1613461123.456][DEBUG]: DevTools HTTP Request failed
qemu: unknown option 'type=utility'
[1613461123.511][DEBUG]: DevTools HTTP Request: http://localhost:9222/json/version
[1613461123.514][DEBUG]: DevTools HTTP Request failed
[1613461123.566][DEBUG]: DevTools HTTP Request: http://localhost:9222/json/version
[1613461123.569][DEBUG]: DevTools HTTP Request failed
[1613461123.620][DEBUG]: DevTools HTTP Request: http://localhost:9222/json/version
[1613461123.632][DEBUG]: DevTools HTTP Request failed
[1613461123.699][DEBUG]: DevTools HTTP Request: http://localhost:9222/json/version
[1613461123.707][DEBUG]: DevTools HTTP Request failed
[1613461123.773][DEBUG]: DevTools HTTP Request: http://localhost:9222/json/version
[1613461123.782][DEBUG]: DevTools HTTP Request failed

DevTools listening on ws://127.0.0.1:9222/devtools/browser/6eb1d2a6-731f-40b8-a035-bf88182009f6
[1613461123.848][DEBUG]: DevTools HTTP Request: http://localhost:9222/json/version
[408:408:0216/073844.321285:ERROR:network_service_instance_impl.cc(286)] Network service crashed, restarting service.
[408:448:0216/073844.321936:FATAL:gpu_data_manager_impl_private.cc(407)] GPU process isn't usable. Goodbye.
qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
[1613461124.337][DEBUG]: DevTools HTTP Request failed
[1613461124.388][DEBUG]: DevTools HTTP Request: http://localhost:9222/json/version
[1613461124.391][DEBUG]: DevTools HTTP Request failed
[1613461124.442][DEBUG]: DevTools HTTP Request: http://localhost:9222/json/version
[1613461124.444][DEBUG]: DevTools HTTP Request failed
[1613461124.500][DEBUG]: DevTools HTTP Request: http://localhost:9222/json/version
[1613461124.503][DEBUG]: DevTools HTTP Request failed
[1613461124.506][INFO]: [63aa62df9dba026b1791fe97928d0082] RESPONSE InitSession ERROR unknown error: Chrome failed to start: crashed.
  (chrome not reachable)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
[1613461124.507][DEBUG]: Log type 'driver' lost 0 entries on destruction
[1613461124.507][DEBUG]: Log type 'browser' lost 0 entries on destruction
[1613461124.508][DEBUG]: Log type 'performance' lost 0 entries on destruction
```

I haven't looked into it more though.

**Comment by alextiley1** [comment]
Hi @soulgalore. Thank you for your response and yes, I would really like to work together with you to try get this resolved. :) 

If I run `docker run --platform linux/arm64 --rm -v "$(pwd)":/browsertime sitespeedio/browsertime:test https://www.sitespeed.io/ -b chrome --chrome.enableChromeDriverLog --chrome.enableVerboseChromeDriverLog -n 1`. Chrome does not seem to start for me at all, my output looks like this:

```
Google Chrome 88.0.4324.150
Mozilla Firefox 84.0
Microsoft Edge 89.0.774.14 dev
[2021-02-16 08:17:24] INFO: Running tests using Chrome - 1 iteration(s)
[2021-02-16 08:17:27] INFO: chrome failed to start, trying 2 more time(s): unknown error: Chrome failed to start: crashed.
  (chrome not reachable)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
[2021-02-16 08:17:29] INFO: chrome failed to start, trying 1 more time(s): unknown error: Chrome failed to start: crashed.
  (chrome not reachable)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
[2021-02-16 08:17:31] INFO: chrome failed to start, trying 0 more time(s): unknown error: Chrome failed to start: crashed.
  (chrome not reachable)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
[2021-02-16 08:17:31] ERROR: BrowserError: Could not start chrome with 3 tries
    at SeleniumRunner.start (/usr/src/app/lib/core/seleniumRunner.js:86:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2021-02-16 08:17:31] ERROR: No data to collect
[2021-02-16 08:17:31] INFO: Wrote data to browsertime-results/www.sitespeed.io/2021-02-16T081723+0000
```

I still think this could be down to the docker file installing the x86 and amd64 versions of the browsers on this line for [edge](https://github.com/sitespeedio/docker-browsers/blob/53c957eb80a3bf32952dd79bd0962454e56a7bdb/Dockerfile#L34), this for [firefox](https://github.com/sitespeedio/docker-browsers/blob/53c957eb80a3bf32952dd79bd0962454e56a7bdb/Dockerfile#L46) and this for [chrome](https://github.com/sitespeedio/docker-browsers/blob/53c957eb80a3bf32952dd79bd0962454e56a7bdb/Dockerfile#L54), from what I understand there is no arm64 version of chrome, and [chromium should be used instead. So some sort of architecture check, and then if its arm64, a chromium (`apt-get install -y chromium-browser`) install instead of a chrome install? This is just an idea for now though.

**Comment by znerd** [comment]
This is still a problem with Sitespeed 21.6.1 running through Docker 20.10.10 on macOS 12.2:

```
% docker run --rm -v "$(pwd):/sitespeed.io" --platform linux/amd64 sitespeedio/sitespeed.io:21.6.1 -b chrome https://www.mindcurv.com/
Google Chrome 97.0.4692.99
Mozilla Firefox 94.0
Microsoft Edge 97.0.1072.69
[2022-02-02 10:06:21] INFO: Versions OS: linux 5.10.47-linuxkit nodejs: v16.13.1 sitespeed.io: 21.6.1 browsertime: 14.18.1 coach: 7.0.0
[2022-02-02 10:06:23] INFO: Running tests using Chrome - 3 iteration(s)
[2022-02-02 10:06:26] INFO: chrome failed to start, trying 2 more time(s): unknown error: Chrome failed to start: crashed.
  (chrome not reachable)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
[2022-02-02 10:07:26] INFO: chrome failed to start, trying 1 more time(s): Failed to start chrome in 60 seconds.
^C
% docker run --rm -v "$(pwd):/sitespeed.io" --platform linux/amd64 sitespeedio/sitespeed.io:21.6.1 -b firefox https://www.mindcurv.com/
Google Chrome 97.0.4692.99
Mozilla Firefox 94.0
Microsoft Edge 97.0.1072.69
[2022-02-02 10:08:21] INFO: Versions OS: linux 5.10.47-linuxkit nodejs: v16.13.1 sitespeed.io: 21.6.1 browsertime: 14.18.1 coach: 7.0.0
[2022-02-02 10:08:23] INFO: Running tests using Firefox - 3 iteration(s)
^C
```

**Comment by soulgalore** [comment]
There are some work for Selenium in https://github.com/SeleniumHQ/docker-selenium/issues/1076 and it looks like they got Chrome to work (I didn't when I tried). 

One of the problems is to keep browser versions in sync between releases (the ARM container will probably be one or two versions behind). 

It will also make the Docker files more complicated since you they will have if/else depending on the architecture. As I understand (and when I tried) you cannot have two different Docker files and push them with the same name but have different architectures.

I haven't had time to look into this more, but I think the simplest way to get it to work is to use Chromium and do not care about the version.
